### ISSUE TITLE
Update published version of docs

### ISSUE THREAD

**Issue by lornajane** [apache/couchdb-documentation#126]
The instructions for contributing to the CouchDB documentation (I'm reading this here: http://docs.couchdb.org/en/2.0.0/contributing.html) reference the main repo but the docs are now in (this!) separate repo.  The source here has already been updated, so would it be possible to regenerate the documentation to reflect this and any other recent changes?

**Comment by wohali** [comment]
Hi @lornajane,

The docs for 2.0.0 are at this point frozen. You can see the correct instructions here:

http://docs.couchdb.org/en/latest/contributing.html

When we release 2.1.0 the instructions will update.

**Comment by rnewson** [comment]
@wohali, can we revisit this approach? It seems to me we should be able to fix broken documentation about 2.0 outside of the release cycle.

**Comment by wohali** [comment]
@rnewson Fair enough. We'll have to move the 2.0.0 tag on the documentation repo to make it happen. But that requires cherry picking the specifics to make it happen. Are you volunteering? ;)

**Comment by rnewson** [comment]
tags are (should be) immutable, so not quite that. All I'm saying is that the docs for a release can improve (grammar, spelling, prose) separately to the code and we should allow for it (and publish it). So the docs could be tagged 2.0.0 for the release but then (say) 2.0.0-1, 2.0.0-2 as we have doc-only improvements.

For this issue itself, perhaps it's enough to get 2.1 out, I just wanted to raise the more general topic for the future.

**Comment by wohali** [comment]
Agree in general. The problem is that readthedocs.org (which drives docs.couchdb.org) goes off of tags, so if the 2.0.0 tag is immutable, the place just about everyone goes for CouchDB documentation (online, not a local copy) won't reflect those changes.

That's what I was reacting to in this filed issue, since it too points at our online version, not the local version. We'd have to lay down a new tag like 2.0.0-2 I guess and convince readthedocs to track it; the further problem then is getting Google and the like to ignore the older versions (which I guess we could technically de-publish.)
