### ISSUE TITLE
2.x doco for _purge is incorrect as it is not implemented

### ISSUE THREAD

**Issue by gbiellem** [apache/couchdb-documentation#197]
Moved from https://github.com/apache/couchdb/issues/965 to here.

The _purge API in the 2.x is not correct.  If called the return code is 501 Not Implemented

Seems purge was left out intentionally according to https://issues.apache.org/jira/browse/COUCHDB-2851 and will be implemented for 2.x in a future release https://issues.apache.org/jira/browse/COUCHDB-3326

As well as the this doco being incorrect there is also no mention of it not being implemented in the breaking changes or known issues for 2.0 or 2.1

**Comment by cepm-nate** [comment]
Kinda hard to believe that they dropped the ball on this one. Now there is no way to "clean out" an existing database. (Deleting and recreating a DB is a horrible enterprise solution) The issue on JIRA was last updated in April 2017, and from another post they said it "should be within a couple months" of Aug 2017. Let's hope we see it soon.

**Comment by wohali** [comment]
We're adding this back in now, the work is critical for the upcoming EU law changes.

I'm going to close this doc bug out since the functionality is coming back shortly.

**Comment by Zeppelin15** [comment]
So this issue was reported nov 2017? 
I understand users can't demand features to be implemented but putting a warning on the docs doesn't seem unreasonable. something like https://github.com/apache/couchdb-documentation/pull/329

**Comment by wohali** [comment]
We totally dropped the ball on fixing up the docs, but at this point, the functionality is ready to go...so fixing the docs is now officially Too Late (tm) :)

**Comment by Zeppelin15** [comment]
> We totally dropped the ball on fixing up the docs, but at this point, the functionality is ready to go...so fixing the docs is now officially Too Late (tm) :)

That's great news! 

Is there any chance of updating the docs for previous versions (including the current 2.20) retrospectively? Perhaps a warning to update to the "new version" in order to use the /_purge endpoint.

Otherwise version specific documentation ( E.g http://docs.couchdb.org/en/2.2.0/api/database/misc.html) will still give the impression a doc purge is possible

I find myself in the scenario where I promised a "doc purge" like feature would be possible based on the docs. Don't t want others to make the same mistake.

**Comment by wohali** [comment]
Unfortunately, no, not at this time, due to a mismatch in intent between ReadTheDocs.org (our docs builder/hoster, which goes off of git tags) and the ASF (who insist that tags not move once placed down).

We're investigating alternative solutions, but don't have any at this time.

Once 2.3.0 releases, 2.2.0 docs will autoredirect to 2.3.0, so this is a short-lived problem at least.
