### ISSUE TITLE
 NodeJS Query Server, missing documentation

### ISSUE THREAD

**Issue by johs** [apache/couchdb-documentation#286]
http://docs.couchdb.org/en/2.1.1/experimental.html?highlight=query%20server#nodejs-query-server
This is reported not to work.

If anyone have any documentation for how to use this, I would be interested in testing it.
Nodejs server via proxy can be used in combination with rewrite as a function, when this bug is fixed https://github.com/apache/couchdb/issues/1407

**Comment by wohali** [comment]
Hi @johs, thanks for the report.

Unfortunately we never fixed/shipped that code with 2.x, so I'm dropping it from the docs for now. If it gets fixed in the main repo we can restore the docs easily enough. However, I expect couch-chakra to take over from the node-based query server as discussed in apache/couchdb#1334.
