### ISSUE TITLE
Enhance nginx reverse proxy support for subdirectory hosting

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-documentation#413]
Comes from: https://github.com/apache/couchdb/issues/2035

Describe how to configure nginx as a reverse proxy where CouchDB is not being hosted at the top level `/` directory, but in a subdirectory like `https://load.balancer.com/couchdb`.

The current instructions prevent Fauxton from working correctly.

@garrensmith @adrienverge is this a limitation of Fauxton or requires reconfiguration of Fauxton somehow, do you know?

**Comment by adrienverge** [comment]
Hi @wohali,

I just tried to access Fauxton at `http://localhost:8080/db/_utils/`, with CouchDB behind a nginx reverse proxy at `/db/`, and I get the same result as in apache/couchdb#2035: Fauxton loads correctly, databases are listed, but opening one fails with `Unexpected token < in JSON at position 0`. By looking at the *network tab* in my browser, it seems that failure comes from an erroneous access to `http://localhost:8080/test` instead of `http://localhost:8080/db/test`:
![Capture d’écran de 2019-05-23 08-19-42](https://user-images.githubusercontent.com/5244945/58230304-44598680-7d34-11e9-8f6a-547f2459976f.png)

I would say it's a *bug* or *limitation* of Fauxton, not a configuration problem, because:
- Fauxton successfully loads `_all_dbs`, databases infos, and `_all_docs` inside databases: it is able to use the reverse-proxied URL without any extra conf.
- I briefly looked into [Fauxton code](https://github.com/apache/couchdb-fauxton/blob/master/settings.json.default.json) and did not find any configuration option to pass a sub-URL.

So in my opinion, it's not documentation to improve here, but a problem to fix in https://github.com/apache/couchdb-fauxton.

**Comment by wohali** [comment]
@adrienverge Thanks, I'll move the ticket to Fauxton.
