### ISSUE TITLE
Update instructions to include CentOS/RHEL 8.

### ISSUE THREAD

**Issue by ghost** [apache/couchdb-documentation#551]
The installation instructions do not mention CentOS/RHEL 8, however, the build bots claim to be making and testing packages: https://ci.couchdb.org/job/jenkins-cm1/job/FullPlatformMatrix/job/3.x/

## Expected Behavior
Instructions should also include CentOS/RHEL 8.

**Comment by wohali** [comment]
Hey @adpopescu-ibm , 

Yup, the packages are there. A pull request to fix the docs would be most welcome!

**Comment by wohali** [comment]
Just an FYI, the CI jobs aren't what build the actual release packages...that's done manually (by policy).

If you just cut & paste the section for RHEL/CentOS 7 for 8 and do the appropriate substitution in the docs, that'll be the correct information.

Note that packages are only available for 8 from 3.1.0 and up, due to JavaScript dependency changes.
